mqtt:
  broker-url: tcp://localhost:1883
  client-id: devicesServiceClient
server:
  servlet:
    context-path: /api
spring:
  application:
    name: devices-service
  datasource:
    url: jdbc:postgresql://localhost:5432/evidentor
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
