mqtt:
  broker-url: tcp://localhost:1883
  client-id: devicesServiceClient
server:
  port: 8081
  servlet:
    context-path: /api
spring:
  application:
    name: devices-service
  datasource:
    url: jdbc:postgresql://localhost:5432/evidentor
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  grpc:
    client:
      decision:
        host: localhost
        port: 9092
    server:
      port: 9091
      reflection:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
debug: false
